use_frameworks!

target 'FlowCore_Example' do
  pod 'FlowCore', :path => '../'

  target 'FlowCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
